apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-manager
  labels:
    io.kompose.service: build-manager
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 2
        maxUnavailable: 0
  selector:
    matchLabels:
      io.kompose.service: build-manager
  template:
    metadata:
      labels:
        io.kompose.service: build-manager
    spec:
      containers:
      - name: build-manager
        image: eiachh/build-manager
        imagePullPolicy: "Never"
        env:
        - name: "PYTHONUNBUFFERED"
          value: "1"
        ports:
        - containerPort: 5001